### ISSUE TITLE
Unknown Connection Failure

### ISSUE THREAD

**Issue by chrisgilldc** [ajmarks/ajmarks_ha_components#4]
Good morning!

Trying to get the integration going, and I'm getting this error:

`2021-01-28 09:46:22 ERROR (MainThread) [custom_components.ge_kitchen.config_flow] Unkown connection failure
Traceback (most recent call last):
  File "/config/custom_components/ge_kitchen/config_flow.py", line 33, in validate_input
    _ = await async_get_oauth2_token(session, data[CONF_USERNAME], data[CONF_PASSWORD])
  File "/usr/local/lib/python3.8/site-packages/gekitchen/async_login_flow.py", line 63, in async_get_oauth2_token
    code = parse_qs(urlparse(resp.headers['Location']).query)['code'][0]
`

Wondering if this might relate to the latest HA patches for custom component security?

This is running core-2021.1.5 on supervisor-2021.01.7.

**Comment by chrisgilldc** [comment]
Okay, appears my password manager was just out of sync with the site itself. Reset and it all works. I did test it to see if this could be choking on any special characters, which has happened on other integrations. All set.
